org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.125
neo_version_range=[21.1.115,)
loader_version_range=[4,)

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

registrate_version = MC1.21-1.3.0+62

create_version = 6.0.1-18
flywheel_minecraft_version = 1.21.1
flywheel_version = 1.0.1-11
flywheel_version_range = [1.0.0-alpha,2.0)
ponder_version = 1.0.39
jei_minecraft_version = 1.21.1
jei_version = 19.21.0.247
curios_minecraft_version = 1.21.1
curios_version = 9.2.2
sodium_version = 0.6.9

# mod options
mod_id=create_d2d
mod_name=Create: Desires 2 Dreams
mod_license=MIT & ARR
mod_version=2.0.0
mod_group_id=dev.lopyluna.create_d2d
mod_authors=LopyLuna
mod_description=A mod of Qol