modLoader = "javafml"
loaderVersion = "[${forge_version},)"
license = "MIT"
issueTrackerURL = "https://github.com/LopyLuna/Create-Dreams-and-Desires/issues"

[[mods]]
modId = "create_dd"
version = "${version}"
displayName = "Create: Dreams & Desires"
# JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/create-dreams-desires"
logoFile = "pack.png"
authors = "LopyLuna"

displayTest = "MATCH_VERSION"

description = '''
Random QoL, items, & blocks that relate to old Create & New Create versions!
'''

[[dependencies.create_dd]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_dd]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_dd]]
modId = "create"
mandatory = true
versionRange = "${create_version}"
ordering = "NONE"
side = "BOTH"